In [29]:
import pandas as pd 

interview_data=pd.read_excel('merged_interniew_category.xlsx') #면접 질문을 직군 별로 나눈 엑셀 파일을 데이터 프레임으로 받아오기 

### 데이터 프레임을 받는 함수 생성

In [30]:
def get_df(file): #파일명을 입력값으로 받는다.
    interview_data=pd.read_excel(file)
    return interview_data

In [31]:
interview_data=get_df('merged_interniew_category.xlsx')
interview_data

Question Category
0     A/B Test 등 현상 분석 및 실험 설계 상 통계적으로 유의미함의 여부를 결정하...  데이터 분석가
1                                Agile 방법론이 무엇인지 설명해주세요  데이터 분석가
2                                 Bias를 통제하는 방법은 무엇입니까?  데이터 분석가
3                           Java에서 Builder 패턴을 사용하는이유는?  데이터 분석가
4                          Java에서 팩토리 메서드 패턴을 사용하는 이유는?  데이터 분석가
...                                                 ...      ...
2901                      Event Delegation에 대해 설명해주십시오.    프론트엔드
2902                                    PWA에 대해 말씀해주세요.    프론트엔드
2903                            웹 저장소의 종류와 특징을 설명해 보세요.    프론트엔드
2904                                   웹 워커에 대해서 말해주세요.    프론트엔드
2905                                 웹 컴포넌트에 대해 말씀해주세요.    프론트엔드

[2906 rows x 2 columns]

In [32]:
interview_data.info() #면접 질문 데이터에 대한 널값과 데이터 타입 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2906 entries, 0 to 2905
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Question  2906 non-null   object
 1   Category  2906 non-null   object
dtypes: object(2)
memory usage: 45.5+ KB


In [33]:
interview_data['Category'].value_counts() #카테고리별 데이터 개수 확인

Category
백엔드           1378
데이터 사이언티스트     490
프론트엔드          456
데이터 엔지니어       302
데이터 분석가        280
Name: count, dtype: int64

### Konlpy란

한글 자연어 처리를 위한 패키지로 아래의 기능을 가진다.

형태소 분석: 한국어 텍스트를 형태소 단위로 분리하고 품사를 태깅한다.

토큰화: 문장을 단어나 형태소 단위로 나누는 기능을 제공한다.



주요 기능:

morphs(): 텍스트에서 형태소를 추출한다.

nouns(): 텍스트에서 명사를 추출한다.

pos(): 텍스트의 품사 정보를 태깅한다.

In [34]:
from konlpy.tag import Okt #konlpy의 Okt 형태소 분석기를 받아온 후 문장이 들어오면 어근을 분리하는 함수 생성, konlpy패키지 별도 설치 필요


okt=Okt() 
def okt_tokenizer(sentence):
    okt_token=okt.morphs(sentence) #.morphs로 텍스트를 형태소 단위로 나눈다
    return okt_token

okt_tokenizer(interview_data.iloc[0,0])



['A',
 '/',
 'B',
 'Test',
 '등',
 '현상',
 '분석',
 '및',
 '실험',
 '설계',
 '상',
 '통계',
 '적',
 '으로',
 '유',
 '의미',
 '함',
 '의',
 '여부',
 '를',
 '결정',
 '하기',
 '위',
 '한',
 '방법',
 '에는',
 '어떤',
 '것',
 '이',
 '있을까요',
 '?']

In [35]:
interview_data['Question'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2906 entries, 0 to 2905
Series name: Question
Non-Null Count  Dtype 
--------------  ----- 
2906 non-null   object
dtypes: object(1)
memory usage: 22.8+ KB


In [36]:
question_cleasinged=interview_data['Question'].values.astype('str') #면접 질문 데이터(interview_data)의 question컬럼의 데이터 타입을 str로 변경

In [37]:
question_cleasinged

array(['A/B Test 등 현상 분석 및 실험 설계 상 통계적으로 유의미함의 여부를 결정하기 위한 방법에는 어떤 것이 있을까요?',
       'Agile 방법론이 무엇인지 설명해주세요', 'Bias를 통제하는 방법은 무엇입니까?', ...,
       '웹 저장소의 종류와 특징을 설명해 보세요.', '웹 워커에 대해서 말해주세요.',
       '웹 컴포넌트에 대해 말씀해주세요.'], dtype='<U192')

### 불용어 처리란
언어 처리에서 의미를 가지지 않거나 분석에 큰 도움이 되지 않는 일반적인 단어들을 말한다. ex) 그 , 저, 입니다.

불용어의 주요 특징:

텍스트에 빈번하게 등장하지만 문맥적으로 중요한 의미를 갖지 않습니다.

텍스트 분석 시 제거되어 처리 효율성을 높이고 분석의 정확도를 개선합니다.

작업의 목적과 언어에 따라 불용어 목록이 달라질 수 있습니다.

In [38]:
stop_words=pd.read_csv('korean_stopwords.txt') #불용어 처리를 위해 korean_stopwords.txt의 파일을 불러온다.

In [39]:
stop_words_interview=stop_words['불용어'].tolist() #불용어 리스트를 생성
stop_words_interview

['진짜',
 '생각',
 '이제',
 '보고',
 '완전',
 '아',
 '휴',
 '어',
 '나',
 '따라',
 '의해',
 '을',
 '를',
 '에',
 '의',
 '가',
 '으로',
 '로',
 '에게',
 '의거하여',
 '근거하여',
 '입각하여',
 '기준으로',
 '예하면',
 '예를 들면',
 '예를 들자면',
 '저',
 '다른',
 '물론',
 '또한',
 '그리고',
 '비길수 없다',
 '해서는 안된다',
 '만이 아니다',
 '만은 아니다',
 '막론하고',
 '관계없이',
 '그치지 않다',
 '그러나',
 '그런데',
 '하지만',
 '든간에',
 '설사',
 '비록',
 '더라도',
 '아니면',
 '만 못하다',
 '하는 편이 낫다',
 '향하여',
 '향해서',
 '향하다',
 '쪽으로',
 '틈타',
 '이용하여',
 '타다',
 '오르다',
 '제외하고',
 '이 외에',
 '이 밖에',
 '하여야',
 '비로소',
 '한다면 몰라도',
 '외에도',
 '이곳',
 '여기',
 '부터',
 '기점으로',
 '따라서',
 '할 생각이다',
 '하려고하다',
 '이리하여',
 '그리하여',
 '그렇게 함으로써',
 '하지만',
 '일때',
 '할때',
 '앞에서',
 '중에서',
 '보는데서',
 '으로써',
 '로써',
 '까지',
 '일것이다',
 '반드시',
 '한다면',
 '등',
 '등등',
 '제',
 '겨우',
 '단지',
 '다만',
 '할뿐',
 '대해서',
 '대하여',
 '대하면',
 '훨씬',
 '얼마나',
 '얼마만큼',
 '얼마큼',
 '남짓',
 '여',
 '얼마간',
 '약간',
 '다소',
 '좀',
 '조금',
 '다수',
 '몇',
 '얼마',
 '지만',
 '하물며',
 '또한',
 '그러나',
 '그렇지만',
 '하지만',
 '이외에도',
 '대해 말하자면',
 '뿐이다',
 '다음에',
 '반대로',
 '반대로 말하자면',
 '이와 반대로',
 '만약',
 '그렇지않으면',
 '툭

Tf-idf는 Term frequency-inverse document frequency의 약자.

TF(Term Frequency)는 특정 문서 내에서 단어가 얼마나 자주 등장하는지를 나타내는 지표

- 한 문서 내에서 많이 등장하는 단어는 중요!
(단순 빈도로 계산)

IDF(Inverse Document Frequency)는 단어의 전체 문서 집합에서 얼마나 희귀한 단어인지를 나타내는 지표

- 한 문서 내에서 희소하게 등장하는 단어는 다른 문서와 구별해주므로 중요!
(전체 문서에서 해당 단어가 포함된 문서의 개수를 나눈뒤 로그)
 
TF-IDF는 TF와 IDF를 곱하여 단어의 중요도를 계산. 특정 문서에서 자주 등장하면서 전체 문서에서는 희귀한 단어일수록 TF-IDF 값이 높아져 이를 통해 텍스트 데이터에서 특정 단어의 중요도를 평가하고, 문서 간의 단어 비교와 검색에서 사용할 수 있다.

### 주요 파라미터

ngram_range: 단어 시퀀스의 범위를 지정한다.

max_features: 벡터화 과정에서 고려할 최대 특성(단어) 수를 지정한다. 

use_idf: IDF 가중치를 적용할지 여부를 결정한다. 기본값은 True이다.

sublinear_tf: TF 값에 대해 1+log(tf) 스케일링을 적용할지 결정한다.

min_df, max_df: 문서 빈도의 최소값과 최대값을 지정하여 너무 희귀하거나 흔한 단어를 제외할 수 있다.

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer #Tfidf벡터화를 통해 각각의 어근을 피쳐로 갖는 희소행렬을 생성, stop_words 파라미터를 통해 불용어 제거


tfidf=TfidfVectorizer(tokenizer=okt_tokenizer,ngram_range=(1,2),stop_words=stop_words_interview ,lowercase=False,) #파라미터는 추후 모델 성능을 비교하며 조정
tfidf.fit(question_cleasinged)
tfidf_interview_data=tfidf.transform(question_cleasinged)
tfidf_interview_data

c:\Users\82106\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\82106\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:406: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['\t', '가서', '각하', '간', '같다면', '같은', '같이', '거나', '걸', '견지', '결론', '고려', '곳', '공동', '관', '관계', '관련', '구체', '그러한', '그런', '그럼에도', '그렇게', '그치지', '근거', '기대', '기점', '기준', '김', '까닭', '나머지', '남', '낫다', '낼', '년도', '누가', '다', '다시', '달려', '답', '대로', '대하', '더', '더욱이', '도', '동시', '됏', '되는', '되다', '되면', '되어', '된', '된다', '될것이다', '두번째', '뒤', '든', '든지', '들면', '들자면', '듯', '따르는', '따름', '때문', '라', '라도', '라면', '리하', '마자', '막론', '만', '만으로', '만은', '만이', '만큼', '만하', '많은', '말', '면', '모른다', '몰라도', '몰랏다', '못', '바', '바꿔', '밖에', '반대', '방면', '번째', '보다', '보아', '본대', '불구', '비', '비교', '비길수', '비추어', '뿐', '상대', '서', '서술', '수', '시작', '시초

<2906x14483 sparse matrix of type '<class 'numpy.float64'>'
	with 46189 stored elements in Compressed Sparse Row format>

In [42]:
tfidf_interview_data.shape #tfidf벡터화한 행렬의 크기

(2906, 14483)

In [43]:
tfidf_interview_data.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### 위 과정을 통해 tfidf벡터화된 행렬을 반환하는 함수 생성

In [44]:
def get_tfidf(data_file,sentence_column,stop_words_file): #data_file=인터뷰 데이터 파일,sentence_column=텍스트 데이터에 해당하는 컬럼 인덱스,stop_words_file=불용어 파일
    
    interview_data=pd.read_excel(data_file)
    question_cleasinged=interview_data.iloc[:,sentence_column].values.astype('str')
    
    stop_words=pd.read_csv(stop_words_file)
    stop_words_interview=stop_words['불용어'].tolist()
    
    tfidf=TfidfVectorizer(tokenizer=okt_tokenizer,ngram_range=(1,2),max_df=1.0,min_df=0.0, stop_words=stop_words_interview,lowercase=False)
    tfidf.fit(question_cleasinged)
    tfidf_interview_data=tfidf.transform(question_cleasinged)
    tfidf_interview_data
    
    return tfidf_interview_data

In [45]:
from sklearn.preprocessing import LabelEncoder

category=interview_data['Category'].values
# LabelEncoder를 객체로 생성한 후 , fit( ) 과 transform( ) 으로 label 인코딩 수행. 
encoder = LabelEncoder()
encoder.fit(category)#학습
category_encoded = encoder.transform(category)#숫자로 변환
print('인코딩 변환값:',category_encoded)

인코딩 변환값: [0 0 0 ... 4 4 4]


In [46]:
interview_data['Category'].value_counts().index

Index(['백엔드', '데이터 사이언티스트', '프론트엔드', '데이터 엔지니어', '데이터 분석가'], dtype='object', name='Category')

In [47]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['데이터 분석가' '데이터 사이언티스트' '데이터 엔지니어' '백엔드' '프론트엔드']


In [48]:
print('디코딩 원본 값:',encoder.inverse_transform([0,1,2,3,4]))

디코딩 원본 값: ['데이터 분석가' '데이터 사이언티스트' '데이터 엔지니어' '백엔드' '프론트엔드']


### 위 과정을 통해 인코딩 반환값을 배열로 반환하는 함수 지정

In [49]:
def category_encoding(df, category_index): #입력값으로 데이터 프레임과 인코딩할 컬럼의 인덱스를 받는다.
    category=df.iloc[:,category_index].values
    encoder = LabelEncoder()
    encoder.fit(category)
    category_encoded = encoder.transform(category)
    return category_encoded

In [50]:
interview_data['category_encoded']=category_encoded

In [51]:
interview_data

Question Category  \
0     A/B Test 등 현상 분석 및 실험 설계 상 통계적으로 유의미함의 여부를 결정하...  데이터 분석가   
1                                Agile 방법론이 무엇인지 설명해주세요  데이터 분석가   
2                                 Bias를 통제하는 방법은 무엇입니까?  데이터 분석가   
3                           Java에서 Builder 패턴을 사용하는이유는?  데이터 분석가   
4                          Java에서 팩토리 메서드 패턴을 사용하는 이유는?  데이터 분석가   
...                                                 ...      ...   
2901                      Event Delegation에 대해 설명해주십시오.    프론트엔드   
2902                                    PWA에 대해 말씀해주세요.    프론트엔드   
2903                            웹 저장소의 종류와 특징을 설명해 보세요.    프론트엔드   
2904                                   웹 워커에 대해서 말해주세요.    프론트엔드   
2905                                 웹 컴포넌트에 대해 말씀해주세요.    프론트엔드   

      category_encoded  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
...                ...  
2901                 4  
2902                 4  
2903                 4  
2904                 4  
2905                 4  

[2906 rows x 3 columns]

In [ ]:
tfidf_interview_data.toarray() #증강+기존

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [55]:
interview_data.iloc[:1453,:]#원본 문제만 해당

Question Category  \
0     A/B Test 등 현상 분석 및 실험 설계 상 통계적으로 유의미함의 여부를 결정하...  데이터 분석가   
1                                Agile 방법론이 무엇인지 설명해주세요  데이터 분석가   
2                                 Bias를 통제하는 방법은 무엇입니까?  데이터 분석가   
3                           Java에서 Builder 패턴을 사용하는이유는?  데이터 분석가   
4                          Java에서 팩토리 메서드 패턴을 사용하는 이유는?  데이터 분석가   
...                                                 ...      ...   
1448               이벤트 위임(Event Delegation)에 대해 설명해주세요.    프론트엔드   
1449               Progressive Web App(PWA)에 대해 설명해주세요.    프론트엔드   
1450             브라우저 저장소(Web Storage)의 종류와 특징을 설명해주세요.    프론트엔드   
1451                       웹 워커(Web Worker)에 대해 설명해주세요.    프론트엔드   
1452                 웹 컴포넌트(Web Components)에 대해 설명해주세요.    프론트엔드   

      category_encoded  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
...                ...  
1448                 4  
1449                 4  
1450                 4  
1451                 4  
1452                 4  

[1453 rows x 3 columns]

In [57]:
tfidf_interview_data.toarray()[:1453,:]#원본 문제만 해당

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
clustered_interview=get_df('merged_interniew_category _cluster.xlsx')#문제+유형

In [66]:
clustered_interview

Question Category  \
0     A/B Test 등 현상 분석 및 실험 설계 상 통계적으로 유의미함의 여부를 결정하...  데이터 분석가   
1                                Agile 방법론이 무엇인지 설명해주세요  데이터 분석가   
2                                 Bias를 통제하는 방법은 무엇입니까?  데이터 분석가   
3                           Java에서 Builder 패턴을 사용하는이유는?  데이터 분석가   
4                          Java에서 팩토리 메서드 패턴을 사용하는 이유는?  데이터 분석가   
...                                                 ...      ...   
2901                      Event Delegation에 대해 설명해주십시오.    프론트엔드   
2902                                    PWA에 대해 말씀해주세요.    프론트엔드   
2903                            웹 저장소의 종류와 특징을 설명해 보세요.    프론트엔드   
2904                                   웹 워커에 대해서 말해주세요.    프론트엔드   
2905                                 웹 컴포넌트에 대해 말씀해주세요.    프론트엔드   

                     Cluster  
0             통계적 분석 및 실험 설계  
1             통계적 분석 및 실험 설계  
2             통계적 분석 및 실험 설계  
3             통계적 분석 및 실험 설계  
4             통계적 분석 및 실험 설계  
...                      ...  
2901      JavaScript 실행 메커니즘  
2902  프론트엔드 최신 기술 및 브라우저 API  
2903  프론트엔드 최신 기술 및 브라우저 API  
2904  프론트엔드 최신 기술 및 브라우저 API  
2905  프론트엔드 최신 기술 및 브라우저 API  

[2906 rows x 3 columns]

In [67]:
clustered_interview['Question_clustered']=clustered_interview['Question']+clustered_interview['Cluster']

In [73]:
tfidf_question_clustered=get_tfidf('merged_interniew_category _cluster.xlsx',2,'korean_stopwords.txt')

c:\Users\82106\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\82106\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:406: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['\t', '가서', '각하', '간', '같다면', '같은', '같이', '거나', '걸', '견지', '결론', '고려', '곳', '공동', '관', '관계', '관련', '구체', '그러한', '그런', '그럼에도', '그렇게', '그치지', '근거', '기대', '기점', '기준', '김', '까닭', '나머지', '남', '낫다', '낼', '년도', '누가', '다', '다시', '달려', '답', '대로', '대하', '더', '더욱이', '도', '동시', '됏', '되는', '되다', '되면', '되어', '된', '된다', '될것이다', '두번째', '뒤', '든', '든지', '들면', '들자면', '듯', '따르는', '따름', '때문', '라', '라도', '라면', '리하', '마자', '막론', '만', '만으로', '만은', '만이', '만큼', '만하', '많은', '말', '면', '모른다', '몰라도', '몰랏다', '못', '바', '바꿔', '밖에', '반대', '방면', '번째', '보다', '보아', '본대', '불구', '비', '비교', '비길수', '비추어', '뿐', '상대', '서', '서술', '수', '시작', '시초

In [ ]:
tfidf_question_clustered.toarray()# 문제+유형파일 tfidf벡터화

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])